//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapaBobs.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public decimal SmallSizePrice { get; set; }
        public decimal MediumSizePrice { get; set; }
        public decimal LargeSizePrice { get; set; }
        public decimal RegularCrustPrice { get; set; }
        public decimal ThinCrustPrice { get; set; }
        public decimal ThickCrustPrice { get; set; }
        public decimal SausagePrice { get; set; }
        public decimal PepperoniPrice { get; set; }
        public decimal OnionsPrice { get; set; }
        public decimal GreenPeppersPrice { get; set; }
    }
}
